version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: freelancemanager_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: freelancemanager_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - freelancemanager_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: freelancemanager_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - freelancemanager_network

networks:
  freelancemanager_network:
    driver: bridge

volumes:
  postgres_data:
